// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*blockPropertiesMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (b BlockProperties) MarshalJSON() ([]byte, error) {
	type BlockProperties struct {
		TxHash         *common.Hash   `json:"txHash,omitempty"`
		InnerBlockHash common.Hash    `json:"innerBlockHash"`
		Coinbase       common.Address `json:"coinbase"`
		Difficulty     *hexutil.Big   `json:"difficulty"`
		GasLimit       *hexutil.Big   `json:"gasLimit"`
		Timestamp      hexutil.Uint64 `json:"timestamp"`
		BaseFeePerGas  *hexutil.Big   `json:"baseFeePerGas,omitempty"`
	}
	var enc BlockProperties
	enc.TxHash = b.TxHash
	enc.InnerBlockHash = b.InnerBlockHash
	enc.Coinbase = b.Coinbase
	enc.Difficulty = (*hexutil.Big)(b.Difficulty)
	enc.GasLimit = (*hexutil.Big)(b.GasLimit)
	enc.Timestamp = hexutil.Uint64(b.Timestamp)
	enc.BaseFeePerGas = (*hexutil.Big)(b.BaseFeePerGas)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (b *BlockProperties) UnmarshalJSON(input []byte) error {
	type BlockProperties struct {
		TxHash         *common.Hash    `json:"txHash,omitempty"`
		InnerBlockHash *common.Hash    `json:"innerBlockHash"`
		Coinbase       *common.Address `json:"coinbase"`
		Difficulty     *hexutil.Big    `json:"difficulty"`
		GasLimit       *hexutil.Big    `json:"gasLimit"`
		Timestamp      *hexutil.Uint64 `json:"timestamp"`
		BaseFeePerGas  *hexutil.Big    `json:"baseFeePerGas,omitempty"`
	}
	var dec BlockProperties
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.TxHash != nil {
		b.TxHash = dec.TxHash
	}
	if dec.InnerBlockHash != nil {
		b.InnerBlockHash = *dec.InnerBlockHash
	}
	if dec.Coinbase != nil {
		b.Coinbase = *dec.Coinbase
	}
	if dec.Difficulty != nil {
		b.Difficulty = (*big.Int)(dec.Difficulty)
	}
	if dec.GasLimit != nil {
		b.GasLimit = (*big.Int)(dec.GasLimit)
	}
	if dec.Timestamp != nil {
		b.Timestamp = uint64(*dec.Timestamp)
	}
	if dec.BaseFeePerGas != nil {
		b.BaseFeePerGas = (*big.Int)(dec.BaseFeePerGas)
	}
	return nil
}
